es (20 sloc)  306 Bytes
   
---
apiVersion: v1
kind: Service
metadata:
  namespace: openhackteam3
  name: tripviewer-svc
  labels:
    app: tripviewer
    env: development
    owner: team3
spec:
  type: ClusterIp
  ports:
    - name: http
      port: 80
      protocol: TCP

selector:
    app: wildfly-dev
    env: development
    owner: team3
